// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh6nXkARljCebgr3qX0MVv26wrCWjVYZA',
    appId: '1:678173915157:web:1386cada05c23526c8761c',
    messagingSenderId: '678173915157',
    projectId: 'chat-app-flutter-83c63',
    authDomain: 'chat-app-flutter-83c63.firebaseapp.com',
    storageBucket: 'chat-app-flutter-83c63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYmVk0G5sgdPD9rHBVYruw290vJI-_0OQ',
    appId: '1:678173915157:android:201c2f9601412cfdc8761c',
    messagingSenderId: '678173915157',
    projectId: 'chat-app-flutter-83c63',
    storageBucket: 'chat-app-flutter-83c63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbsAStMWuQXPa5VCQ4KYVTB26deQjFbl0',
    appId: '1:678173915157:ios:bbe41db0fddb5164c8761c',
    messagingSenderId: '678173915157',
    projectId: 'chat-app-flutter-83c63',
    storageBucket: 'chat-app-flutter-83c63.appspot.com',
    iosClientId: '678173915157-qh1bvddh69qg7uisodatrkrjqu8jf31c.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbsAStMWuQXPa5VCQ4KYVTB26deQjFbl0',
    appId: '1:678173915157:ios:bbe41db0fddb5164c8761c',
    messagingSenderId: '678173915157',
    projectId: 'chat-app-flutter-83c63',
    storageBucket: 'chat-app-flutter-83c63.appspot.com',
    iosClientId: '678173915157-qh1bvddh69qg7uisodatrkrjqu8jf31c.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
